# https://taskfile.dev

version: '2'

tasks:

  charts.release:
    cmds:
      - helm lint helm-chart-sources/*
      - helm package -u helm-chart-sources/*
      - helm repo index --url https://mrmuggymuggy.github.io/helm-charts .
